### ISSUE TITLE
Upgrading the mod to 0.17

### ISSUE THREAD

**Issue by PaladinFallen** [axtox/exoskeleton-mark-ii#1]
just wondering mate, cause i really enjoyed the mod and even fixed it til one update. But it's now out of my knowledge to repair. just wondering if you are coming back?

**Comment by axtox** [comment]
Hello friend, yes I'm currently working on it. Gonna update this mod to 0.17 in a week! Thank you for your interest, I'm glad that this mod is still useful for someone!
So did you fork this repo or created a clone?--
Anton



Jun 18, 2019, 2:35 AM by notifications@github.com:

**Comment by PaladinFallen** [comment]
i honestly started with your code and tweaked all the settings (for my personal use... and my brother cause he plays with me sometimes... to work for .17, HOWEVER there was one update that broke everything that I did. It was when I first created armor and placed it on myself the game would crash, I tried to figure out the problem but it was one thing after another IRL. So I created a fork with everything that I did to help you out, but even so I'm still not done uploading everything.

**Comment by axtox** [comment]
Okay great 
I can look at it in this weekend, I'm back from.my vacation!
Thank you for your interest, I will defentely take a good look to your fork and hopefully togherer we can merge our changes!--
Anton



Jun 18, 2019, 6:00 AM by notifications@github.com:

**Comment by axtox** [comment]
Good, started to work on this. Please, take a look to the pull requests.
In future it would me much easier to have all commits that are about single change (new feature or patch) under 1 pull request

**Comment by PaladinFallen** [comment]
Sorry about that still new to this github, I've made a fork to the control.lua and removed what i know can be removed. However, i'm still playing around with to figure out what changes was made to break it.

**Comment by axtox** [comment]
Great job, I've merged everything to the `upgrade-0.17` branch, I will contionue work there until it will be fully fixed!
Thank you so much for your work and time, it helped a lot!

**Comment by PaladinFallen** [comment]
you need to take file:  exoskeleton-mark-ii/graphics/exoskeleton-mark-ii-tech.png  and copy it to the main folder and rename it thumbnail.png (i can't upload files or I would have done that). Also the last update that I did to control.lua fixed it. The mod is up and running.
